# Generated by Django 4.1.7 on 2023-05-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='part',
            field=models.CharField(default='A01001', max_length=32),
            preserve_default=False,
        ),
    ]
