# Generated by Django 4.1.7 on 2023-04-18 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_plan_remove_customuser_group_delete_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='discount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Размер скидки в процентах'),
        ),
    ]
