# Generated by Django 4.1.7 on 2023-04-18 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_plan_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='discount',
            field=models.FloatField(unique=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Размер скидки в процентах'),
        ),
    ]
