# Generated by Django 4.1.7 on 2023-04-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='users.plan')),
            ],
        ),
    ]
