# Generated by Django 4.1.7 on 2023-04-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'покупатель'), ('supplier', 'продавец')], default='customer', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
