# Generated by Django 4.1.7 on 2023-04-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_role_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('seeker', 'покупатель'), ('supplier', 'продавец')], default='seeker', max_length=32),
        ),
    ]
