# Generated by Django 4.1.7 on 2023-05-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='1234567890', max_length=16, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
