# Generated by Django 4.1.7 on 2023-05-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='multiplier',
            field=models.DecimalField(decimal_places=4, default=1.5, max_digits=8, verbose_name='Множитель тарифа'),
            preserve_default=False,
        ),
    ]
