version: '3.9'

services:

  # db:
  #   image: postgres:15-alpine
  #   volumes:
  #     - /var/lib/postgresql/data/
  #   env_file:
  #     - ./.env

  web:
    build: ../
    
    container_name: web
    restart: unless-stopped
    volumes:
      - static_value:/app/static/dist/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env


  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/

      # - ../static/dist/:/var/html/static/
      # - ../media/:/var/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web


volumes:
  static_value:
  media_value: