version: '3.9'

services:

  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env-dev
    ports:
      - "5432:5432"


  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ../tsenhub-frontend/dist/:/usr/share/nginx/html/
      - ../static/:/var/html/static/
      - ../static/:/var/html/media/
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf


volumes:
  static_value:
  media_value:
