version: '3.9'

services:

  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    volumes:
      - ./db_storage:/var/lib/postgresql/data/
    env_file:
      - ./.env-dev
    ports:
      - "5432:5432"

  web:
    # image: sergeiban/zapchastitsa
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    volumes:
       - static_volume:/app/static/
       - media_volume:/app/media/
       - app_volume:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      # - ./.env-dev
      - ./.env


  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ../tsenhub-frontend/dist/:/usr/share/nginx/html/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    depends_on:
      - web
  
  celery:
    image: sergeiban/zapchastitsa-celery
    restart: unless-stopped
    env_file:
      - ./.env-dev
    command: ["celery", "-A", "project", "worker", "-l", "info"]
    depends_on:
      - redis
    volumes:
      - app_volume:/app/


volumes:
  static_volume:
  media_volume:
  db_volume:
  app_volume:
