version: '3.9'

services:

  # db:
  #   image: postgres:15-alpine
  #   volumes:
  #     - /var/lib/postgresql/data/
  #   env_file:
  #     - ./.env


  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ../static/dist/:/var/html/static/
      - ../media/:/var/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf