version: '3.9'

services:
  frontend:
    image: sergeiban/zapchastitsa-frontend 
    container_name: frontend
    volumes:
      - frontend_volume:/app/dist/
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  web:
     image: sergeiban/zapchastitsa 
     container_name: web
     restart: unless-stopped
     volumes:
       - static_volume:/app/static/
       - media_volume:/app/media/
       - app_volume:/app/
     ports:
       - "8000:8000"
     depends_on:
       - db
     env_file:
       - ./.env

  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_volume:/usr/share/nginx/html/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
 
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    depends_on:
      - web

  celery:
    image: sergeiban/zapchastitsa-celery
    env_file:
      - ./.env
    command: ["celery", "-A", "project", "worker", "-l", "info"]
    depends_on:
      - redis
    volumes:
      - app_volume:/app/
 
    #certbot:
    #image: certbot/certbot
    #volumes:
    # - ./certbot/conf:/etc/letsencrypt
    #  - ./certbot/www:/var/www/certbot
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email zapchastitsa@internet.ru -d xn--80aaazh4bpi1bf.xn--p1ai --agree-tos  


volumes:
  static_volume:
  media_volume:
  frontend_volume:
  app_volume:
