version: '3.9'

services:
  frontend:
    image: sergeiban/zapchastitsa-frontend
    container_name: frontend
    volumes:
      - frontend_volume:/app/dist/
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env-prod
    ports:
      - "5432:5432"
    depends_on:
      - frontend

  web:
     image: sergeiban/zapchastitsa 
     container_name: web
     restart: unless-stopped
     volumes:
       - static_volume:/app/static/
       - media_volume:/app/media/
     ports:
      - "8000:8000"
     depends_on:
       - db
     env_file:
       - ./.env-prod
  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - frontend_volume:/usr/share/nginx/html/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web


volumes:
  static_volume:
  media_volume:
  frontend_volume:
