# Generated by Django 4.1.7 on 2023-04-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_part_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
    ]
