# Generated by Django 4.1.7 on 2023-05-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_remove_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='part',
            name='uid',
            field=models.CharField(max_length=32),
        ),
    ]
