# Generated by Django 4.1.7 on 2023-05-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-date'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
